import type { Metadata } from "next";
import { Ubuntu } from "next/font/google";
import "./globals.css";
import QueryProvider from "@/components/providers/QueryProvider";

const ubuntu = Ubuntu({
  subsets: ["cyrillic"],
  weight: "700"
});

export const metadata: Metadata = {
  title: "Doc-Space",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${ubuntu.className} antialiased`}
      >
        <QueryProvider>
          {children}
        </QueryProvider>
      </body>
    </html>
  );
}
