import type { Metadata } from "next";
import { Ubuntu } from "next/font/google";
import "./globals.css";
import QueryProvider from "@/components/providers/QueryProvider";
import { ThemeProvider } from "@/components/providers/ThemeProvider";
import Navigation from "@/components/shared/Navigation";
import { ScrollToTopButton } from "@/components/shared/ScrollToTop";
import { Toaster } from "@/components/ui/toaster";

const ubuntu = Ubuntu({
	subsets: ["cyrillic"],
	weight: "700",
});

export const metadata: Metadata = {
	title: "Doc-Space",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={`${ubuntu.className} antialiased`}>
				<QueryProvider>
					<ThemeProvider
						attribute="class"
						defaultTheme="system"
						enableSystem
						disableTransitionOnChange
					>
						<div
							className="min-h-screen bg-gradient-to-br 
							from-slate-50 via-blue-50 to-purple-100
							dark:from-gray-900 dark:via-zinc-900 dark:to-neutral-800 transition-colors duration-300"
						>
							<Navigation />
							{children}
							<Toaster />
							<ScrollToTopButton />
						</div>
					</ThemeProvider>
				</QueryProvider>
			</body>
		</html>
	);
}
